export const DISPLAY_MATCH = 'DISPLAY_MATCH';
export const DISPLAY_HIGHLIGHTS = 'DISPLAY_HIGHLIGHTS';
export const DISPLAY_STANDINGS = 'DISPLAY_STANDINGS';
export const DISPLAY_COLLECTION = 'DISPLAY_COLLECTION';
export const ADD_VIDEO = 'ADD_VIDEO';
export const FIND_NEXT_FIXTURE = 'FIND_NEXT_FIXTURE';
export const SET_TOKEN = 'SET_TOKEN';

export const SIGNUP = 'SIGNUP';
export const SIGNIN = 'SIGNIN';

